"""initial migrations

Revision ID: a77c6b237fe0
Revises: 
Create Date: 2026-09-03 19:26:25.308715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77c6b237fe0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('products',
    sa.Column('stock_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('stock_code')
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice', sa.String(length=50), nullable=False),
    sa.Column('stock_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='chk_sales_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='chk_sales_quantity_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_code'], ['products.stock_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index('idx_sales_cust_stock_date', 'sales', ['customer_id', 'stock_code', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_invoice'), 'sales', ['invoice'], unique=False)
    op.create_index(op.f('ix_sales_invoice_date'), 'sales', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_sales_stock_code'), 'sales', ['stock_code'], unique=False)
    op.create_table('returns',
    sa.Column('return_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice', sa.String(length=50), nullable=False),
    sa.Column('stock_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='chk_returns_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='chk_returns_quantity_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['products.stock_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('return_id')
    )
    op.create_index(op.f('ix_returns_sale_id'), 'returns', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_returns_sale_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_sales_stock_code'), table_name='sales')
    op.drop_index(op.f('ix_sales_invoice_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_invoice'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index('idx_sales_cust_stock_date', table_name='sales')
    op.drop_table('sales')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
